<?php

namespace BlogBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function showNews()
    {
        // $em = $this->getEntityManager();
        // $query = $em->createQuery(
        //     ' SELECT u
        //       FROM BlogBundle:News u
        //       LIMIT :limit OFFSET 0
        //     '
            //setParameter permet de declarer la variable passer en parametre de la fonction
        //)->setParameter('limit', $limit);
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            ' SELECT u
              FROM BlogBundle:News u
              ORDER BY u.date DESC
            '
            //setParameter permet de declarer la variable passer en parametre de la fonction
        )->setMaxResults(3);
        
        return $query->execute();

    }

}
