<?php

namespace ForumBundle\Repository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends \Doctrine\ORM\EntityRepository
{
    public function showMessage($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT m
             FROM ForumBundle:Forum m
             WHERE m.categorie = :id
             ORDER BY m.date DESC'
        )->setParameter('id', $id);

        return $query->execute();
    }
}
